dictionarys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
]+ static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web import views


app_name ="web"


urlpatterns = [
    path ("", views.index, name="index"),
    path("create_word/",views.create_word,name="create_word"),
    path("<str:pk>/edit_word/",views.edit_word,name="edit_word"),
  
]

web/models.py
import uuid
from django.db import models


class Word(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    word = models.CharField(max_length=100)
    is_edit = models.BooleanField(default=False)
   
    def _str_(self):
        return str(self.word)


class WordMeaning(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    word = models.ForeignKey("web.Word", on_delete=models.CASCADE)
    meaning = models.TextField()
    examples = models.TextField()
    synonyms = models.TextField()
    priority = models.IntegerField(null=True)
   

    def _str_(self):
        return str(self.word)

web/views.py
from django.shortcuts import render, get_object_or_404, redirect
from web.models import Word, WordMeaning

def index(request):
    if request.method == 'POST':
        search_word = request.POST.get('search_word')
        error_msg = False
        error = "The word '{}' is not found"
        
        if search_word == '':
            error_msg = "Empty Search"
            context = {
                "title": "Dictionary",
                "word": search_word,
                "show": True,
                "error_msg": error_msg,
            }
            return render(request, 'web/index.html', context)
            
        word = Word.objects.filter(word=search_word)
        if word:
            word_meaning = WordMeaning.objects.filter(word__in=word).order_by('priority')
            word=Word.objects.filter(word=search_word)
            context = {
                "title": "Dictionary",
                "meanings": word_meaning,
                "word": search_word,
                "show": True,
                "words":word
            }
            return render(request, 'web/index.html', context)
        
        error_msg = error.format(search_word)
        context = {
            "title": "Dictionary",
            "word": search_word,
            "show": True,
            "error_msg": error_msg,
        }
        return render(request, 'web/index.html', context)
    
    context = {
        "title": "Dictionary",
        "searchword": "",
        "word": "",
        "show": False,
    }
    return render(request, 'web/index.html', context)


def create_word(request):
    if request.method == 'POST':
        word = request.POST.get('word')
        meaning = request.POST.get('word_meaning')
        priority = request.POST.get('priority')
        synonyms = request.POST.get('word_synonyms')
        examples = request.POST.get('word_examples')

        new_word, created = Word.objects.get_or_create(
            word=word
        )
        if created:
            WordMeaning.objects.create(
                word=new_word,
                meaning=meaning,
                synonyms=synonyms,
                examples=examples,
                priority=priority,
            )
            redirect('/')

    context = {
        "title": "Adding word to dictionary"
    }
    return render(request, "web/addword.html", context)


def edit_word(request, pk):
    word_instance = Word.objects.get(id=pk)
    if word_instance:
        if WordMeaning.objects.filter(word=word_instance).exists():
            word_meaning_instance = WordMeaning.objects.get(word=word_instance)

    
    
    if request.method == "POST":
        word = request.POST.get("edited-text")
        meaning = request.POST.get("edited-word-meaning")
        priority = request.POST.get('priority')
        synonyms = request.POST.get('edited-word-synonyms')
        examples = request.POST.get('edited-word-examples')
        print(meaning)
        print(word)
        
        
        if word:
            word_instance.word = word
            word_meaning_instance.meaning=meaning
            word_meaning_instance.priority=priority
            word_meaning_instance.synonyms=synonyms
            word_meaning_instance.examples=examples
            word_meaning_instance.save()
         

        return redirect('/')  # Assuming you have a word_detail view

    context = {
        "title": "Edit Page",
        "word_meaning_instance": word_meaning_instance,
        "word_instance": word_instance,
        "word_id": pk
    }
    return render(request, "web/edit.html", context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dictionary App</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="wrapper">
        <div class="searchBox">
            <header>English Dictionary</header>
            <div class="heading">
                <a class="button" href="{% url 'dictionary:search a word' %}">Add Word</a>
            </div>
           
    
            <form action="" method="get">
                    <img src="{% static './images/Property 1=serach.svg' %}" />
                  
                    <input type="text" name="search" placeholder="Search a Word" >                 
            </form>
    
                   
            <ul> 
                <div class="content">
                    <li class="meaning">
                        <div class="details">
                            <p>Meaning</p>
                            <span>feeling or showing pleasure or content</span>
                        </div>
                    </li>
                    <li class="example">
                        <div class="details">
                            <p>Example</p>
                            <span>feeling or showing pleasure or content</span>
                        </div>
                    </li>
                    <li class="synonyms">
                        <div class="details">
                            <p>Synonyms</p>
                            <div class="list">
                                <span>Glag ,</span>
                                <span>Contented ,</span>
                                <span>Delighted ,</span>
                                <span>Cheerful ,</span>
                                <span>Joyful </span>
                            </div>
                        </div>
                    </li>
                </div>
            </ul>
        </div>
    </div>

   
</body>
</html>

templates/web/addword.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
        <link rel="stylesheet" href="{% static './css/add.css' %}" />
    </head>
    <body>
        <section class="container">
            <form action="{% url 'web:create_word' %}" method="post" >
                {% csrf_token %}
                <div class="form-field">
                    <label for="word">Enter a word :-</label>
                    <input id='word' type="text" name="word" />
                </div>
                <div class="form-field">
                    <label for="word_meaning">Meaning :-</label>
                    <textarea name="word_meaning" id="word_meaning" cols="30" rows="10"></textarea>
                </div>
                <div class="form-field">
<<<<<<< HEAD
                    <label for="word_synonyms">Synonyms :-</label>
                    <textarea name="word_synonyms" id="word_synonyms" cols="30" rows="10"></textarea>
                </div>
                <div class="form-field">
                    <label for="word_examples">Examples :-</label>
                    <textarea name="word_examples" id="word_examples" cols="30" rows="10"></textarea>
=======
                    <label for="word_meaning">Synonys:-</label>
                    <textarea name="word_meaning" id="word_meaning" cols="30" rows="10"></textarea>
                </div>
                <div class="form-field">
                    <label for="word_meaning">Example :-</label>
                    <textarea name="word_meaning" id="word_meaning" cols="30" rows="10"></textarea>
>>>>>>> 6adce3a08294b59c147631778dd6ebb8a3fa7429
                </div>
                <div class="form-field">
                    <label for="Priority">Priority :-</label>
                    <select name="priority" id="Priority">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>
                <div class="form-field btn">
                    <input type="submit" value="Add word" />
                    <div><a href="{% url 'web:index' %}">Go Back</a></div>
                    
                </div>

templates/web/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
        <link rel="stylesheet" href="{% static './css/add.css' %}" />
    </head>
    <body>
        
        <section class="container">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-field">
                    <label for="word">Word :-</label>
                    <input id='word' type="text" name="edited-text" value="{{word_instance.word}}"/>
                </div>
                <div class="form-field">
                    <label for="word_meaning">Word meaning :-</label>
                    <input id="word_meaning"  type="text" name="edited-word-meaning" value="{{word_meaning_instance.meaning}}"/>
                </div>
                <div class="form-field">
                    <label for="word_synonyms">Word Synonyms :-</label>
                    <input id="word_synonyms"  type="text" name="edited-word-synonyms" value="{{word_meaning_instance.synonyms}}"/>
                </div>
                <div class="form-field">
                    <label for="word_examples">Word examples :-</label>
                    <input id="word_examples"  type="text" name="edited-word-examples" value="{{word_meaning_instance.examples}}"/>
                </div>
                <div class="form-field">
                    <label for="Priority">Priority :-</label>
                    <select name="priority" id="Priority">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>
                    <div class="form-field btn">
                        <button class="edit">Edit</button>
                        <a href="{% url 'web:index' %}">Go Back</a>
                    </div>
            </form>
        </section>
    
    </body>
    </html>

templates/web/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
        <link rel="stylesheet" href="{% static './css/dict-style.css' %}" />
    </head>
    <body>
        <section class="container">
            
            <div class="heading">
                <h3>English Dictionary</h3>
                <a class="button" href="{% url 'web:create_word' %}">Add Word</a>
                {% if meanings %}
                  {% for word in words %}
                   
                <div>
                    <a href="{% url 'web:edit_word' pk=word.id %}" class="edit_word">Edit</a>
                </div>
                {% endfor %}
                  
                {% endif %}
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-field">
                    <input type="text" placeholder="Search for a word..." name="search_word" />
                    <button type="submit" class="submit-btn">
                        <img src="{% static './images/Property 1=serach.svg' %}" alt="Search" />
                    </button>
                </div>
            </form>
            <ul class="result" >
                {% if show %}
                    <h2>{{word}}</h2>
                    {% if error_msg %}
                        <p class="error">{{error_msg}}</p>
                    {% endif %}
                    <h4>Meaning</h4>
                    {% for meaning in meanings %}
                        <li>
                            {{meaning.meaning}}
                        </li>
                    {% endfor %}
                    <h4>Synonyms</h4>
                    {% for meaning in meanings %}
                        <li>
                            {{meaning.synonyms}}
                        </li>
                    {% endfor %}
                    <h4>Examples</h4>
                    {% for meaning in meanings %}
                        <li>
                            {{meaning.examples}}
                        </li>
                    {% endfor %}
                {% else %}
                    <li>
                        <h2>Search a word</h2>
                    </li>
                {% endif %}
            </ul>

        </section>
        
    </body>
</html>